name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      working-directory: bacon-dotnet
      run: dotnet restore
    - name: Build
      working-directory: bacon-dotnet
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: bacon-dotnet
      run: dotnet test --no-restore --verbosity normal
